version: '3.1'
services:
  golang:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    environment:
      - AWS_PROFILE
    volumes:
      - ~/.aws:/root/.aws:ro
